#!/usr/bin/env bash

# Script used to do a backup on USB disk using Borg.

SCRIPT_PATH=$(realpath ${0})
WORKING_DIR=$(dirname ${SCRIPT_PATH})
EXCLUDE_FILE=${WORKING_DIR}/borg.exclude
ARCHIVE=$(date +%F)
BACKUP_PATH="/home/benoit/backup/home"

source ${WORKING_DIR}/borg.conf

export BORG_REPO="${BORG_DEVICE}${BACKUP_PATH}"

echo "N'oubliez pas de démarrer le HTPC et de débloquer la clé SSH pour s'y connecter"
read

# Create the backup archive
borg create --verbose --progress --stats --compression lzma,6 --exclude-from ${EXCLUDE_FILE} ::${ARCHIVE} /home/benoit

# Prune backup archives by keeping the 7 last daily backup archives plus 3 last monthly backup archives
# Using the options --dry-run --list may be useful to list which backup archives are kept/pruned
borg prune --verbose --stats --keep-daily=7 --keep-monthly=3 ${BORG_REPO}

# Sync to cloud using rclone
rclone -v --transfers ${RCLONE_NB_FILE_TRANSFERS} sync ${RCLONE_SOURCE_NAME}:${BACKUP_PATH} ${RCLONE_DESTINATION_NAME}:${RCLONE_DESTINATION_PATH}
